# Application name
spring.application.name=inz

# File upload directory (use a path inside the container)
file.upload-dir=/app/images
python.backend-url=${PY_BACKEND:http://localhost:5001}
origin.allowed=${FRONTEND_ORIGIN:http://localhost:3000}

# File upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=400MB

# Database configuration (using Docker container name, not localhost)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/inz
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Secret key
SECRET_KEY=64270262d085586675f10aec71ae903ce8d746161b85e99d86369f0cbdf0238616738b3a212e908a5814487451487562d18421c607a119224b6338feb7c34e06468222ce4b0a5432925ab7d7a19c3da0bf2347cd21c0f486942968d2ad9cb66fe4859c63c0f9925bb38d68ce287e8609152129088e473b8c04b7bbe92165365b

# JPA (Hibernate) settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Global CORS config for API
spring.mvc.cors.enabled=true
spring.mvc.cors.mapping=/api/**
spring.mvc.cors.allowed-origins=${FRONTEND_ORIGIN:http://localhost:3000}
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true
